from build_ranges import build

inputs = build("CALCULOS!K12",
               "CALCULOS!L14",
               "RESULTADOS FACTURAS ESTIMADAS!B4", 
               "RESULTADOS FACTURAS ESTIMADAS!B5:D10", 
               "RESULTADOS FACTURAS ESTIMADAS!B11:C12", 
               "RESULTADOS FACTURAS ESTIMADAS!B20:B24",
               "RESULTADOS FACTURAS ESTIMADAS!G4:T1",
               "RESULTADOS FACTURAS ESTIMADAS!G16:T16",
               "RESULTADOS ANÁLISIS CONSUMO!B3:B14",
               "RESULTADOS ANÁLISIS CONSUMO!O3:Q3",
               "RESULTADOS ANÁLISIS CONSUMO!B21",
               "RESULTADOS ANÁLISIS CONSUMO!B47",
               "RESULTADOS ANÁLISIS CONSUMO!B73",
               "RESULTADO GENERACIONvsCONSUMO!C3:V3",
               "RESULTADO GENERACIONvsCONSUMO!C15:V15"
            )