from build_ranges import build

inputs = build("RESULTADOS FACTURAS ESTIMADAS!B4", 
               "RESULTADOS FACTURAS ESTIMADAS!B5:D10", 
               "RESULTADOS FACTURAS ESTIMADAS!B11:C12", 
               "RESULTADOS FACTURAS ESTIMADAS!B20:B24",
               "RESULTADOS FACTURAS ESTIMADAS!G4:T16",
               "RESULTADOS ANÁLISIS CONSUMO!B3:B14",
               "RESULTADOS ANÁLISIS CONSUMO!O3:Q14",
               "RESULTADOS ANÁLISIS CONSUMO!B21",
               "RESULTADOS ANÁLISIS CONSUMO!B47",
               "RESULTADOS ANÁLISIS CONSUMO!B73",
               "RESULTADO GENERACIONvsCONSUMO!C3:V15"
            )